---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nginx-demo-secret
  namespace: nginx-test
spec:
  encryptedData:
    API_KEY: AgB+/GZzbz07embRbv8orVzEozfXiWKpV1IYGDHsKj+YpgPy43gR+lDYHVzgOokze0SHXrIQ41kUBLKa1DUtLKTS8uPXVlO0bhX4diwaN5sBkOW3oQgW+eaAoAp0IfPFgMoia08IxoZ9lDYU7QzFyB2jKK2k/P+hw9mnbAZfEpXECMuC8XcLfZM6o0ROxAVSJXOpmpuh1Xmg61CnY3sIFXof73/2M4i3s/rYxzbS6ahaqVONgqWdPiuqjdbML2Oy6L8E8oxVLZ6bepR7Nf5gJ2tAGSDIiKx6WNYaPTdZHMejqQL+hAYH6bDr9jEmF0mgzruma/zKkageYJp/MQcL3AZAvK6YIAF18Jet8Ls1mI9puWbGPrn/5VbxDnguNPlCNLtpxYxSyHcp5NEZSOqHa4eBf3e1z78GA/5eTXV19LUViq3ui4IHQNHefBoNMTDpbaqvNG+x8scIeGSzN5jUog75c12Dm9CF83SbxYrhFgZ1OqbPDGU0xvgbwjsyTnOxwBV375/pCBmGlw8cIIXUq36Ji4COt5XA25Bjw693/S+yCr1d5DCGd6ac3NU+sVC4ZQ4AIeGKrpNCctDo1ZZtq5OOR0kl3wOM8Kq8Gmw2TsrbR7G0CGsLNT1PS0neSAW4b8bNl/LLaSu2Tg/cFFaCgIY8Rb21Kru04cVIcBIhzwbtPaTk7ha0bOL9mRophdBMU99YW3AQKl4YrfK5lcbIPYN6RLk=
    DB_PASSWORD: AgAHcbHOWti5pmWgVagP4li5QE7mTun2NpOM2yHl2KU3RBKroo/dMwCeeQHClJ+OujPtPaiIdsS//khpY8jDsbir/jmmgpkCrNIb7y6a1/ImqyBmUyc5+ug4wwUyxI9mzpPEu7T+v62GbrPGFsHU2M1lU1GHyTDwGoKn79Nf8QeIrU4cENT9tDwd14bn7rPl1N/lp2gzhACDj142EH8I2J12Qp4UozddBk0Zf4+dNx9Ez5DWk8t72fBdaAgtDYMmvZSibtoODF81Sq4Xm8R/82whZ9CR6YdMVSxX/c4BtmZrtWFY/27ZhEsQ0e6Oh9HDk4/hBkYNWDAl7SOYex7fK/yM4cngadKku4LPpoKMX+Gxr2y6EPhtkUcbBgfyT/JkKax77QBRkHln3m0A8g7600hqZ5BHZI9syc8qaVmaiuMU0/iFrBE1MqrL31JFempyEb/sxgac2jMhAg2T/CDh4ssev8+MxOSQpVJR6volBq3Zl2NYit4IL+J+4FVwuHJZZ2i8EgfwLgv4LurKamo6y/eUX21K4kikw8IUfZlT4yJHv7gQzCUiim82PmPxQVZL75m6y/XUaO0LhHHhyJUKhCFRNkROqYQDxtI1coECjobbIJ7WrAxEJClYsAMXAw9rrah/6bPcCET7tnE4YWbXUFPTT08q3ijcW5gqp4bMfVARtp0tc/eTTxgh+EtFul1wvx5hnUqBl6etoJ4JFjGyTkY2/puZ7fMa
  template:
    metadata:
      name: nginx-demo-secret
      namespace: nginx-test
