apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1" # The Grafana sidecar watches for this label
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-stack.monitoring:3100
        isDefault: false
        jsonData:
          maxLines: 1000
