apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: podinfo-ahaouari-tls
  namespace: ingress-system
spec:
  secretName: podinfo-ahaouari-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - podinfo.ahaouari.com
