apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: podinfo
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "podinfo-role"
        vault.hashicorp.com/agent-inject-secret-redis-password: "homelab/data/podinfo/credentials"
        vault.hashicorp.com/agent-inject-template-redis-password: |
          {{- with secret "homelab/data/podinfo/credentials" -}}
          {{- .Data.data.REDIS_PASSWORD -}}
          {{- end -}}
    spec:
      serviceAccountName: redis-sa
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: redis
          image: redis@sha256:7aec734b2bb298a1d769fd8729f13b8514a41bf90fcdd1f38ec52267fbaa8ee6
          command: ["sh", "-c"]
          args:
            - exec redis-server --requirepass "$(cat /vault/secrets/redis-password)"
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          emptyDir: {}
