---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: podinfo-redis-url
  namespace: podinfo
spec:
  encryptedData:
    REDIS_URL: AgCUwXfzG/48Wd5hOyos1bmWHwPkfWkDcq8t3aYFZ93M4KeACSo/lqvfk8w4mgiF1CHDS/C8Hcytu4N2z0CbtVqYOwa1ORu2z7/6j4sm47b5lARTyFMZFDtodRpcSuxc89wXevGBuqT2IPi+wUP4d4KZjGG07PEiBNpUXFGzHKJNEN+FadXF+VC9QWLg58QRyA73D/An1mOp1ztZKlZZHgF64HlT7P627ybkl6uxnOMdHvorYCaWE8JxN1bIr/UugV0m7dvvJPjYktEXVuQLzxUI6YGe4HEErebpAQNMKt8jr2UB07rSf4yWkDlTSxxvJGzGfGfwEKuxYl2E6gzGmdQ2OKrB8ZNqQB0JBMFI0s2Zfwcycg0K/0cLvm+AJrmMegBhzRcR2J9wM3+ftl4oIamnFeWmypcL/1+BNmPWbkBHk5KzHiX1KNwsea/rpKLEBCkMSSIrst8CNAtwcCT5NfCNiz4ihOMgWW1ycqunCElbOOrK2h4zFPx01Gv3IwOGL89C1v2C0sDDRo1l6M+W9BT+SSd8wWh6bYEI3IZSuee7+K6jX1rcWv0z8gg78Oz/AcepcSBQESKBjn1w+2camJFa67wxIMl9tOLHn0QeRRpEo/GCSbvd9wcFXzT7ee9q9AZbPy1VZgYYUIbir9bBuJTXShyN5yyAkM/fRy+fzdRbObHA7VLy0/F56k/VjGqfSaWgJyrN1vYabr/OvqmMZ7qjqaU6h2FAnEL9KUaapGsbdD/fuHGR04PF81wTe4IPDhwrA/UNQ3I+4xGai6mnG9o=
  template:
    metadata:
      name: podinfo-redis-url
      namespace: podinfo
