---
all:
  children:
    # Global group encompassing the entire cluster
    k8s_cluster:
      children:
        # Subgroup for the Control Plane node(s)
        control_plane:
          hosts:
            k8s-ctrl-01:
              ansible_host: 10.10.20.10

        # Subgroup for the Worker nodes
        workers:
          hosts:
            k8s-work-01:
              ansible_host: 10.10.20.11
            k8s-work-02:
              ansible_host: 10.10.20.12
