apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rexpn-ahaouari-tls
  namespace: ingress-system
spec:
  secretName: rexpn-ahaouari-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - rexpn.ahaouari.com
