apiVersion: apps/v1
kind: Deployment
metadata:
  name: rexpn-app
  namespace: rexpn
  labels:
    app: rexpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rexpn
  template:
    metadata:
      labels:
        app: rexpn
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: harbor.homelab.local/homelab/rexpn-app@sha256:71d51dc8a669cba98d51e3d758cceb4b5eb9cc3456f29f58447c6cc16b662c7a
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
