apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/abdelhaouari/homelab.git"
    path: gitops/manifests/jellyfin
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
