apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homelab-gateway
  namespace: ingress-system
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https-nginx
      protocol: HTTPS
      port: 443
      hostname: nginx.ahaouari.com
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: nginx-ahaouari-tls
    - name: https-grafana
      protocol: HTTPS
      port: 443
      hostname: grafana.ahaouari.com
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: grafana-ahaouari-tls
    - name: https-argocd
      protocol: HTTPS
      port: 443
      hostname: argocd.ahaouari.com
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: argocd-ahaouari-tls
    - name: https-hubble
      protocol: HTTPS
      port: 443
      hostname: hubble.ahaouari.com
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: hubble-ahaouari-tls
    - name: https-podinfo
      protocol: HTTPS
      port: 443
      hostname: podinfo.ahaouari.com
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: podinfo-ahaouari-tls
    - name: https-rexpn
      protocol: HTTPS
      port: 443
      hostname: rexpn.ahaouari.com
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: rexpn-ahaouari-tls
